<div class="appheader">
    <div class="page-main">
        <div class="columns">
            <div class="column main">
                <ul class="userdetails">
                    <li>Gebruiker Veronica Costello</li>
                    <li>Rol Oelewapper</li>
                </ul>
            </div>
            <div class="sidebar-main">
                <div class="illu applogo"></div>
            </div>
        </div>
    </div>
</div>

